### ISSUE TITLE
Стандартизировать работу с GIT

### ISSUE THREAD

**Issue by vladpunko** [Sparklll/python-labs#8]
Теги названы не верно!
Удали лишние теги и называй их одинаково.
Далее я е вижу merge в mated с develop, поправь это!

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by Sparklll** [comment]
Линейная история получилась из-за merge в автоматическом fast-forward режиме. Впредь буду использовать при слиянии merge --no-ff для наглядного понимания, какие изменения происходили, а также буду производить pull request's.
